### ISSUE TITLE
use ANALYZE TABLE to generate statistics

### ISSUE THREAD

**Issue by dynofu** [dyno/facets-overview-spark#5]
https://docs.databricks.com/spark/latest/spark-sql/language-manual/analyze-table.html
looks like it requires hive support

**Comment by dyno** [comment]
https://github.com/dyno/facets-overview-spark/commit/e26eccc27358256c5a6b25fbdb2e6cb058d130b9

**Comment by dyno** [comment]
```
cd ammonites
make ENABLE_HIVE=1 analyzeTable.sc
```
this won't be the solution as  introduce hive dependency is highly undesirable.
